Resources:
  # A role is required for the lambda function, so create one here
  # See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
  hello_apigateway_role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: hello-gateway-lambda
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"

  # See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html
  hello_apigateway:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: your-bucket-here
        S3Key: dart-lambda-example.zip
        S3ObjectVersion: obj-version-here
      Architectures: arm64
      Runtime: provided.al2023
      Handler: hello.apigateway
      Role:
        Fn::GetAtt: [hello_apigateway_role, Arn]
