name: aws_lambda_runtime
version: 1.1.1
description: |-
  A powerful runtime to build Lambda functions in Dart with native AWS events.
homepage: https://github.com/amondnet/aws-lambda-dart-runtime
#documentation: https://awslabs.github.io/aws-lambda-dart-runtime/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  json_annotation: ^4.9.0
  meta: ^1.3.0
  http: ^1.0.0

dev_dependencies:
  json_serializable: ^6.9.5
  build_runner: ^2.1.11
  test: ^1.16.8
  mockito: ^5.0.3
  lints: ^6.0.0
